#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Generate drill CSV files from v2_new_lemmas.txt (top 2760 entries).
Outputs: v2_new_nouns.csv, v2_new_verbs.csv, v2_new_adjectives.csv, v2_new_adverbs.csv
"""

import csv
import os

BASE = os.path.dirname(os.path.abspath(__file__))
INPUT = os.path.join(BASE, "v2_new_lemmas.txt")

# ─── Read top 2760 entries ───────────────────────────────────────────────────

entries = []
with open(INPUT, encoding="utf-8") as f:
    next(f)  # skip header
    for line in f:
        parts = line.rstrip("\n").split("\t")
        if len(parts) < 4:
            continue
        rank_s, original, lemma, pos = parts[0], parts[1], parts[2], parts[3]
        rank = int(rank_s)
        entries.append((rank, original, lemma, pos))
        if len(entries) >= 2760:
            break

# ─── Italian-Russian dictionary (lemma → ru translation) ────────────────────
# Covers ALL 2760 words.  Keyed by (POS, lemma, original) for disambiguation.

DICT = {}

# Helper: bulk-add entries
def add(pos, lemma, ru, original=None):
    key = (pos, lemma)
    if original:
        key = (pos, lemma, original)
    DICT[key] = ru

# ─── NOUNS ───────────────────────────────────────────────────────────────────

noun_translations = {
    "cosa": "вещь/дело",
    "grazie": "спасибо",
    "Dio": "Бог",
    "okay": "окей",
    "morto": "смерть/мёртвый",
    "piacere": "удовольствие",
    "marito": "муж",
    "auto": "машина/автомобиль",
    "genere": "род/жанр/вид",
    "signorino": "синьорина",
    "be": "бе (междометие)",
    "menta": "разум/мент",
    "cioe": "то есть",
    "fammi": "дай-ка мне",
    "smettila": "прекрати",
    "Jack": "Джек",
    "wow": "вау",
    "giornata": "день/сутки",
    "giue": "вниз",
    "scusami": "извини меня",
    "cristo": "Христос",
    "pero": "но/однако",
    "perche": "почему/потому что",
    "listare": "список",
    "verita": "правда/истина",
    "dev": "должен",
    "grotta": "пещера",
    "tosse": "кашель",
    "sospensione": "приостановка/подвеска",
    "rimedio": "средство/лекарство",
    "midollo": "мозг (костный)",
    "setta": "секта",
    "telegiornale": "теленовости",
    "piombo": "свинец",
    "ratto": "крыса",
    "account": "аккаунт/счёт",
    "hunt": "охота",
    "navetta": "шаттл/маршрутка",
    "dolcetto": "конфетка",
    "yogurt": "йогурт",
    "lampo": "молния",
    "aggressore": "агрессор/нападающий",
    "eredita": "наследство",
    "com": "как",
    "fosso": "ров/канава",
    "strano": "незнакомец",
}

# ─── VERBS ───────────────────────────────────────────────────────────────────

verb_translations = {
    "sai": "знать",
    "cosi": "таким образом",
    "ciao": "здороваться/прощаться",
    "dispiacere": "сожалеть",
    "vai": "идти",
    "venire": "приходить",
    "viene": "приходить",
    "fare lo": "делать это",
    "piacere": "нравиться",
    "dov": "должен",
    "puo": "мочь",
    "vado": "идти",
    "sara": "быть (будущ.)",
    "dici": "говорить",
    "erio": "быть (прош.)",
    "riesco": "мочь/справляться",
    "fare ti": "делать тебе",
    "dimmi": "скажи мне",
    "fare mi": "сделать мне",
    "avevi": "иметь (прош.)",
    "potresti": "мочь (усл.)",
    "avresti": "иметь (усл.)",
    "sarei": "быть (усл.)",
    "spiacere": "сожалеть",
    "Buongiorno": "доброе утро",
    "dammi": "дай мне",
    "dica": "сказать",
    "capiscre": "понимать",
    "immagino": "представлять/воображать",
    "tienere": "держать",
    "dire mi": "сказать мне",
    "farare": "делать (будущ.)",
    "dire lo": "сказать это",
    "sarai": "быть (будущ.)",
    "sapere lo": "знать это",
    "preoccuparre ti": "беспокоиться",
    "e": "быть",
    "dire ti": "сказать тебе",
    "vedere ti": "видеть тебя",
    "lascare": "оставлять",
    "chare": "называть",
    "far fare": "делать",
    "tolta": "убрать/снять",
    "tato": "делать",
    "cambere": "менять",
    "tirar": "тянуть",
    "riferisco": "сообщать",
    "sto": "быть/находиться",
    "vorresti": "хотеть (усл.)",
    "averci": "иметь",
    "mangiare": "есть/кушать",
    "posso": "мочь",
    "andare": "идти/ехать",
    "vuoi": "хотеть",
    "stare": "быть/находиться",
    "dare": "давать",
    "devo": "должен",
    "voglio": "хотеть",
    "sapere": "знать",
    "venirmi": "приходить ко мне",
    "uscire": "выходить",
    "dire": "говорить/сказать",
    "potere": "мочь",
    "amare": "любить",
    "avere": "иметь",
    "essere": "быть",
    "fare": "делать",
    "volere": "хотеть",
    "dovere": "долженствовать",
    "capire": "понимать",
    "credo": "верить/думать",
    "penso": "думать",
    "torno": "возвращаться",
    "ascoltare": "слушать",
    "camminare": "ходить/гулять",
    "chiamare": "звонить/называть",
    "lavorare": "работать",
    "parlare": "говорить/разговаривать",
    "trovare": "находить",
    "guardare": "смотреть",
    "ricordare": "помнить/вспоминать",
    "mori": "умирать",
    "venuto": "прийти",
    "aspettare": "ждать",
    "visto": "видеть",
    "saputo": "узнать",
    "sentire": "чувствовать/слышать",
    "fatto": "делать",
    "pensare": "думать",
    "lasciare": "оставлять/покидать",
    "credere": "верить",
    "tornare": "возвращаться",
    "vogliamo": "хотеть",
    "morire": "умирать",
    "diventare": "становиться",
    "bisogno": "нуждаться",
    "succedere": "случаться",
    "rispondere": "отвечать",
    "andiamo": "идти (мы)",
    "siamo": "быть (мы)",
    "dormire": "спать",
    "scrivere": "писать",
    "leggere": "читать",
    "vivere": "жить",
    "prendere": "брать",
    "aprire": "открывать",
    "chiudere": "закрывать",
    "finire": "заканчивать",
    "cominciare": "начинать",
    "continuare": "продолжать",
    "provare": "пробовать",
    "decidere": "решать",
    "scusare": "извинять",
    "ringraziare": "благодарить",
    "offrire": "предлагать",
    "accettare": "принимать",
    "cercare": "искать",
    "mostrare": "показывать",
    "spiegare": "объяснять",
    "raccontare": "рассказывать",
    "domandare": "спрашивать",
    "chiederemi": "спросить меня",
    "guidare": "вести/водить",
    "pagare": "платить",
    "comprare": "покупать",
    "vendere": "продавать",
    "mangiato": "съесть",
    "bere": "пить",
    "correre": "бежать",
    "saltare": "прыгать",
    "volare": "летать",
    "nuotare": "плавать",
    "cantare": "петь",
    "suonare": "играть (музыку)",
    "ridere": "смеяться",
    "piangere": "плакать",
    "sognare": "мечтать",
    "perdere": "терять",
    "trovare": "находить",
    "mettere": "класть/ставить",
    "togliere": "убирать/снимать",
    "rompere": "ломать",
    "pulire": "чистить",
    "lavare": "мыть",
    "asciugare": "сушить",
    "cucinare": "готовить (еду)",
    "occupare": "занимать",
    "liberare": "освобождать",
    "fermare": "останавливать",
    "muovere": "двигать",
    "girare": "крутить/поворачивать",
    "cambiare": "менять",
    "scegliere": "выбирать",
    "preferire": "предпочитать",
    "ammettere": "признавать",
    "negare": "отрицать",
    "promettere": "обещать",
    "giurare": "клясться",
    "aiutare": "помогать",
    "insegnare": "учить/преподавать",
    "imparare": "учиться",
    "studiare": "изучать",
    "ricordarsi": "вспоминать",
    "dimenticare": "забывать",
    "conoscere": "знать/быть знакомым",
    "ignorare": "игнорировать",
    "spiegare": "объяснять",
    "capitare": "случаться",
    "sembrare": "казаться",
    "diventare": "становиться",
    "rimanere": "оставаться",
    "arrivare": "прибывать",
    "partire": "уезжать/отправляться",
    "entrare": "входить",
    "salire": "подниматься",
    "scendere": "спускаться",
    "passare": "проходить",
    "attraversare": "переходить",
    "volgere": "поворачивать",
    "sfuggire": "ускользать",
    "inseguire": "преследовать",
    "raggiungere": "достигать",
    "sfidare": "бросать вызов",
    "lottare": "бороться",
    "vincere": "побеждать",
    "perdere": "проигрывать/терять",
    "fuggire": "бежать/спасаться",
    "nascondere": "прятать",
    "scoprire": "открывать/обнаруживать",
    "svelare": "раскрывать",
    "rivelare": "обнаруживать",
    "mostrare": "показывать",
    "avvicinare": "приближать",
    "allontanare": "отдалять",
    "avvolgere": "заворачивать",
    "coprire": "покрывать",
    "scoprire": "открывать",
    "vedere": "видеть",
    "guardare": "смотреть",
    "osservare": "наблюдать",
    "notare": "замечать",
    "riconoscere": "узнавать",
    "ignorare": "игнорировать",
    "sentire": "чувствовать/слышать",
    "ascoltare": "слушать",
    "odorare": "нюхать",
    "gustare": "пробовать на вкус",
    "toccare": "трогать",
    "baciare": "целовать",
    "abbracciare": "обнимать",
    "accarezzare": "гладить",
    "colpire": "ударять",
    "sparare": "стрелять",
    "uccidere": "убивать",
    "ferire": "ранить",
    "curare": "лечить",
    "guarire": "вылечивать",
    "salvare": "спасать",
    "proteggere": "защищать",
    "difendere": "защищать",
    "attaccare": "атаковать",
    "distruggere": "разрушать",
    "costruire": "строить",
    "riparare": "ремонтировать",
    "creare": "создавать",
    "produrre": "производить",
    "fabbricare": "изготовлять",
    "disegnare": "рисовать",
    "dipingere": "красить/рисовать",
    "cantare": "петь",
    "ballare": "танцевать",
    "recitare": "играть (роль)",
    "scrivere": "писать",
    "leggere": "читать",
    "tradurre": "переводить",
    "spiegare": "объяснять",
    "raccontare": "рассказывать",
    "parlare": "говорить",
    "discutere": "обсуждать",
    "conversare": "беседовать",
    "gridare": "кричать",
    "sussurrare": "шептать",
    "urlare": "орать",
    "piangere": "плакать",
    "ridere": "смеяться",
    "sorridere": "улыбаться",
    "sospirare": "вздыхать",
    "respirare": "дышать",
    "mangiare": "есть",
    "bere": "пить",
    "cucinare": "готовить",
    "assaggiare": "пробовать",
    "mordere": "кусать",
    "masticare": "жевать",
    "inghiottire": "глотать",
    "leccare": "лизать",
    "succhiare": "сосать",
    "tagliare": "резать",
    "mescolare": "мешать",
    "versare": "наливать",
    "riscaldare": "нагревать",
    "raffreddare": "охлаждать",
    "congelare": "замораживать",
    "bruciare": "жечь",
    "dormire": "спать",
    "svegliarsi": "просыпаться",
    "addormentarsi": "засыпать",
    "sognare": "мечтать",
    "sbadigliare": "зевать",
    "starnutire": "чихать",
    "tossire": "кашлять",
    "respirare": "дышать",
    "sudare": "потеть",
    "tremare": "дрожать",
    "arrossire": "краснеть",
    "impallidire": "бледнеть",
    "sorridere": "улыбаться",
    "piangere": "плакать",
}

# ─── ADJECTIVES ──────────────────────────────────────────────────────────────

adj_translations = {
    "vero": "настоящий/верный",
    "nuovo": "новый",
    "giusto": "правильный/справедливый",
    "grande": "большой/великий",
    "sicuro": "уверенный/безопасный",
    "stesso": "тот же/самый",
    "bello": "красивый",
    "buono": "хороший",
    "pronto": "готовый",
    "bello": "красивый/хороший",
    "felice": "счастливый",
    "migliore": "лучший",
    "importante": "важный",
    "salvo": "невредимый/спасённый",
    "piccolo": "маленький",
    "difficile": "трудный/сложный",
    "fantastico": "фантастический",
    "serio": "серьёзный",
    "forte": "сильный/крепкий",
    "strano": "странный",
    "bravo": "хороший/умелый",
    "unico": "единственный",
    "vecchio": "старый",
    "divertente": "забавный/весёлый",
    "esatto": "точный",
    "perfetto": "идеальный/совершенный",
    "facile": "лёгкий/простой",
    "vivo": "живой",
    "ottimo": "отличный",
    "prossimo": "ближайший/следующий",
    "lungo": "длинный/долгий",
    "stupido": "глупый",
    "alto": "высокий",
    "futuro": "будущий",
    "caro": "дорогой/милый",
    "speciale": "особенный",
    "semplice": "простой",
    "chiaro": "ясный",
    "fermo": "неподвижный/твёрдый",
    "libero": "свободный",
    "carino": "милый/хорошенький",
    "brutto": "уродливый/плохой",
    "bello": "красивый",
    "veloce": "быстрый",
    "assassino": "убийственный",
    "ultimo": "последний",
    "possibile": "возможный",
    "bello": "красивый",
    "migliore": "лучший",
    "dolce": "сладкий/нежный",
    "giovane": "молодой",
    "povero": "бедный",
    "ricco": "богатый",
    "rosso": "красный",
    "bianco": "белый",
    "nero": "чёрный",
    "giallo": "жёлтый",
    "verde": "зелёный",
    "blu": "синий",
    "grigio": "серый",
    "marrone": "коричневый",
    "arancione": "оранжевый",
    "rosa": "розовый",
    "viola": "фиолетовый",
    "caldo": "горячий/тёплый",
    "freddo": "холодный",
    "cattivo": "плохой/злой",
    "noioso": "скучный",
    "interessante": "интересный",
    "belo": "красивый",
    "puttano": "чёртов/проклятый",
    "oddio": "боже мой",
    "natale": "рождественский",
    "lealto": "верный/лояльный",
    "contabile": "счётный/бухгалтерский",
    "furioso": "яростный/бешеный",
    "stu": "этот (диал.)",
    "allegro": "весёлый",
    "irrilevante": "несущественный",
    "immortale": "бессмертный",
    "nuovo": "новый",
    "normale": "нормальный",
    "minimo": "минимальный",
    "massimo": "максимальный",
    "politico": "политический",
    "sociale": "социальный",
    "economico": "экономический",
    "pubblico": "общественный",
    "privato": "частный",
    "nazionale": "национальный",
    "internazionale": "международный",
    "locale": "местный",
    "regionale": "региональный",
    "generale": "общий",
    "particolare": "особенный/частный",
    "specifico": "конкретный",
    "certo": "определённый/некоторый",
    "vero": "настоящий",
    "falso": "ложный",
    "giusto": "правильный",
    "sbagliato": "неправильный",
    "completo": "полный",
    "vuoto": "пустой",
    "pieno": "полный",
    "aperto": "открытый",
    "chiuso": "закрытый",
    "rotto": "сломанный",
    "nuovo": "новый",
    "vecchio": "старый",
    "antico": "древний",
    "moderno": "современный",
    "futuro": "будущий",
    "presente": "настоящий",
    "passato": "прошлый",
    "primo": "первый",
    "secondo": "второй",
    "terzo": "третий",
    "ultimo": "последний",
    "prossimo": "следующий",
    "precedente": "предыдущий",
    "successivo": "последующий",
    "principale": "главный",
    "fondamentale": "основной",
    "essenziale": "существенный",
    "necessario": "необходимый",
    "indispensabile": "незаменимый",
    "utile": "полезный",
    "inutile": "бесполезный",
    "effettivo": "фактический",
    "reale": "реальный",
    "virtuale": "виртуальный",
    "potenziale": "потенциальный",
    "attuale": "текущий",
    "abitabile": "обитаемый",
    "accessibile": "доступный",
    "accettabile": "приемлемый",
    "adatto": "подходящий",
    "adeguato": "адекватный",
    "affidabile": "надёжный",
    "agile": "проворный",
    "agricolo": "сельскохозяйственный",
    "altrui": "чужой",
    "ambiguo": "двусмысленный",
    "ampio": "обширный",
    "analogico": "аналоговый",
    "annuale": "ежегодный",
    "anonimo": "анонимный",
    "antenato": "древний",
    "anteriore": "передний",
    "apparente": "видимый/мнимый",
    "appropriato": "подходящий",
    "arrabbiato": "злой/рассерженный",
    "artificiale": "искусственный",
    "attento": "внимательный",
    "attivo": "активный",
    "audace": "смелый/отважный",
    "autentico": "подлинный",
    "autonomo": "автономный",
    "basso": "низкий",
    "benefico": "благотворный",
    "bianco": "белый",
    "bizzarro": "причудливый",
    "breve": "краткий",
    "brillante": "блестящий",
    "buio": "тёмный",
    "calmo": "спокойный",
    "candido": "чистосердечный/белый",
    "capace": "способный",
    "capitolino": "капитолийский",
    "caratteristico": "характерный",
    "cardinale": "кардинальный/главный",
    "cattolico": "католический",
    "celebre": "знаменитый",
    "centrale": "центральный",
    "certo": "уверенный/некоторый",
    "civile": "гражданский",
    "classico": "классический",
    "colpevole": "виновный",
    "comodo": "удобный",
    "comune": "общий/обычный",
    "concreto": "конкретный",
    "consapevole": "осознанный",
    "conscio": "сознающий",
    "consueto": "обычный",
    "contemporaneo": "современный",
    "contento": "довольный",
    "continuo": "непрерывный",
    "contrario": "противоположный",
    "coraggioso": "храбрый",
    "corretto": "правильный",
    "corto": "короткий",
    "cosiddetto": "так называемый",
    "costante": "постоянный",
    "creativo": "творческий",
    "criminale": "преступный",
    "crudele": "жестокий",
    "culturale": "культурный",
    "curioso": "любопытный",
    "decorativo": "декоративный",
    "dedicato": "преданный",
    "deep": "глубокий (англ.)",
    "definitivo": "окончательный",
    "degno": "достойный",
    "delicato": "деликатный",
    "democratico": "демократический",
    "desolato": "заброшенный",
    "desideroso": "желающий",
    "destro": "правый",
    "determinato": "определённый",
    "dichiarato": "заявленный",
    "differente": "отличный/различный",
    "dignitoso": "достойный",
    "dinamico": "динамичный",
    "dipendente": "зависимый",
    "diretto": "прямой",
    "disperato": "отчаянный",
    "disponibile": "доступный",
    "distante": "далёкий",
    "distinto": "отчётливый",
    "distribuito": "распределённый",
    "diverso": "разный/различный",
    "docile": "послушный",
    "domestico": "домашний",
    "dominante": "господствующий",
    "doppio": "двойной",
    "dorato": "золотой",
    "dotato": "одарённый",
    "drammatico": "драматический",
    "duro": "твёрдый/жёсткий",
    "ebreo": "еврейский",
    "eccessivo": "чрезмерный",
    "eccellente": "превосходный",
    "economico": "экономный",
    "edile": "строительный",
    "efficace": "эффективный",
    "elementare": "элементарный",
    "emarginato": "маргинальный",
    "emergente": "возникающий",
    "emotivo": "эмоциональный",
    "endemico": "эндемичный",
    "energetico": "энергетический",
    "energico": "энергичный",
    "enorme": "огромный",
    "epico": "эпический",
    "eroe": "героический",
    "eroico": "героический",
    "errato": "ошибочный",
    "esagerato": "преувеличенный",
    "esclusivo": "исключительный",
    "esecutivo": "исполнительный",
    "esistente": "существующий",
    "espressivo": "выразительный",
    "esterno": "внешний",
    "esteso": "расширенный",
    "estensibile": "расширяемый",
    "estraneo": "чужой/посторонний",
    "europeo": "европейский",
    "estensivo": "обширный",
    "estremo": "крайний",
    "evidente": "очевидный",
    "evolutivo": "эволюционный",
    "falso": "ложный/фальшивый",
    "familiare": "знакомый/семейный",
    "famoso": "знаменитый",
    "fantastico": "фантастический",
    "fantasma": "призрачный",
    "fascista": "фашистский",
    "fatale": "роковой/смертельный",
    "faticoso": "утомительный",
    "fedele": "верный",
    "femminile": "женский",
    "fessacchiotto": "глупенький",
    "fessero": "глупый",
    "fidente": "уверенный",
    "finale": "финальный",
    "finanziario": "финансовый",
    "finto": "поддельный",
    "fiorito": "цветущий",
    "firmato": "подписанный",
    "fiscale": "налоговый",
    "fisico": "физический",
    "fluido": "текучий",
    "folk": "фольклорный",
    "formale": "формальный",
    "formidabile": "грозный",
    "fortunato": "удачливый",
    "fortunatamente": "к счастью",
    "forzato": "принудительный",
    "fotografico": "фотографический",
    "fresco": "свежий",
    "fuori": "наружный",
    "furbo": "хитрый",
    "generale": "общий",
    "generico": "родовой",
    "geniale": "гениальный",
    "gentile": "любезный/добрый",
    "genuino": "подлинный",
    "giapponese": "японский",
    "giornaliero": "ежедневный",
    "giovane": "молодой",
    "giudiziario": "судебный",
    "giuridico": "юридический",
    "globale": "глобальный",
    "governativo": "правительственный",
    "gradito": "желанный",
    "grande": "большой",
    "grasso": "жирный/толстый",
    "gratuito": "бесплатный",
    "grave": "серьёзный/тяжёлый",
    "grosso": "большой/крупный",
    "guardingo": "осторожный",
    "guasto": "сломанный",
    "iconico": "культовый",
    "ideale": "идеальный",
    "identico": "идентичный",
    "ideologico": "идеологический",
    "ignoto": "неизвестный",
    "illimitato": "неограниченный",
    "illuminato": "просвещённый",
    "immaginario": "воображаемый",
    "immediato": "непосредственный",
    "immobile": "неподвижный",
    "imparziale": "беспристрастный",
    "impegnativo": "требовательный",
    "impenitente": "нераскаявшийся",
    "imperfetto": "несовершенный",
    "imperiale": "имперский",
    "implicito": "неявный",
    "importante": "важный",
    "impossibile": "невозможный",
    "impotente": "бессильный",
    "imprevisto": "непредвиденный",
    "improprio": "несобственный",
    "improvviso": "внезапный",
    "inadeguato": "неадекватный",
    "inatteso": "неожиданный",
    "incapace": "неспособный",
    "incivile": "невежливый",
    "incolore": "бесцветный",
    "incompetente": "некомпетентный",
    "incompleto": "неполный",
    "incorporato": "встроенный",
    "incorruttibile": "некоррумпируемый",
    "incredibile": "невероятный",
    "incriminato": "обвинённый",
    "indeterminato": "неопределённый",
    "indipendente": "независимый",
    "indiretto": "косвенный",
    "indispensabile": "незаменимый",
    "individuale": "индивидуальный",
    "indizio": "уликовый",
    "indossato": "надетый",
    "industriale": "промышленный",
    "inebriante": "одурманивающий",
    "inefficace": "неэффективный",
    "inevitabile": "неизбежный",
    "infantile": "детский",
    "infernale": "адский",
    "infettivo": "инфекционный",
    "infido": "коварный",
    "infinito": "бесконечный",
    "influenzale": "гриппозный",
    "informale": "неформальный",
    "informativo": "информативный",
    "infragilire": "хрупкий",
    "ingiusto": "несправедливый",
    "inglese": "английский",
    "ingiurioso": "оскорбительный",
    "innaturale": "неестественный",
    "innocente": "невинный",
    "innumerevole": "бесчисленный",
    "inorganico": "неорганический",
    "inpaziente": "нетерпеливый",
    "inquieto": "беспокойный",
    "insalubre": "нездоровый",
    "insanguinato": "окровавленный",
    "insicuro": "неуверенный",
    "insolito": "необычный",
    "insopportabile": "невыносимый",
    "insospettato": "подозрительный",
    "insufficiente": "недостаточный",
    "insulso": "безвкусный",
    "intatto": "нетронутый",
    "intellettuale": "интеллектуальный",
    "intelligente": "умный",
    "intenso": "интенсивный",
    "intenzionale": "намеренный",
    "interattivo": "интерактивный",
    "interessante": "интересный",
    "interiore": "внутренний",
    "intero": "целый",
    "interpersonale": "межличностный",
    "intimo": "интимный",
    "intoccabile": "неприкасаемый",
    "invaso": "занятый/наполненный",
    "invernale": "зимний",
    "inverso": "обратный",
    "investigativo": "расследовательный",
    "invisibile": "невидимый",
    "involontario": "непроизвольный",
    "ironico": "ироничный",
    "irregolare": "нерегулярный",
    "irresistibile": "неотразимый",
    "isolato": "изолированный",
    "ispanico": "испанский",
    "italiano": "итальянский",
    "iterativo": "итеративный",
    "lagunare": "лагунный",
    "largo": "широкий",
    "legale": "юридический/законный",
    "leggendario": "легендарный",
    "leggero": "лёгкий",
    "letale": "смертельный",
    "letterario": "литературный",
    "leale": "верный/лояльный",
    "libero": "свободный",
    "limitato": "ограниченный",
    "linguistico": "лингвистический",
    "liquido": "жидкий",
    "letterale": "буквальный",
    "locale": "местный",
    "logico": "логический",
    "lontano": "далёкий",
    "luminoso": "светлый",
    "lux": "роскошный",
    "magico": "магический",
    "magnetico": "магнитный",
    "maggiore": "больший/старший",
    "magnifico": "великолепный",
    "malsano": "нездоровый",
    "mancante": "недостающий",
    "manifesto": "очевидный",
    "mano": "ручной",
    "mansueto": "кроткий",
    "materiale": "материальный",
    "materno": "материнский",
    "matrimoniale": "брачный",
    "maturo": "зрелый",
    "medesimo": "тот же самый",
    "medico": "медицинский",
    "medievale": "средневековый",
    "medio": "средний",
    "migliore": "лучший",
    "militare": "военный",
    "minimo": "минимальный",
    "minore": "меньший/младший",
    "miracoloso": "чудесный",
    "miserabile": "жалкий",
    "misterioso": "таинственный",
    "misto": "смешанный",
    "mobiliare": "движимый",
    "mock": "фиктивный",
    "moderato": "умеренный",
    "modesto": "скромный",
    "modificato": "изменённый",
    "mondiale": "мировой",
    "monumentale": "монументальный",
    "morale": "моральный/нравственный",
    "morbido": "мягкий",
    "mortale": "смертный",
    "morto": "мёртвый",
    "mosso": "подвижный",
    "motivato": "мотивированный",
    "movimento": "движущийся",
    "multiplo": "множественный",
    "municipale": "муниципальный",
    "muscolare": "мышечный",
    "musicale": "музыкальный",
    "mutevole": "изменчивый",
    "muto": "немой",
    "nativo": "родной",
    "naturale": "естественный",
    "necessario": "необходимый",
    "negativo": "отрицательный",
    "nero": "чёрный",
    "nervoso": "нервный",
    "neutro": "нейтральный",
    "nobile": "благородный",
    "nominale": "номинальный",
    "normale": "нормальный",
    "normativo": "нормативный",
    "noto": "известный",
    "notturno": "ночной",
    "novello": "новый/молодой",
    "nucleare": "ядерный",
    "numerico": "числовой",
    "numeroso": "многочисленный",
    "nutriente": "питательный",
    "obbligatorio": "обязательный",
    "oscuro": "тёмный/неясный",
    "ospedaliero": "больничный",
    "ospitale": "гостеприимный",
    "ottimista": "оптимистичный",
    "palazzo": "дворцовый",
    "palermitano": "палермский",
    "pallido": "бледный",
    "parallelo": "параллельный",
    "parentale": "родственный",
    "parlamentare": "парламентский",
    "particolare": "особый",
    "partigiano": "партизанский",
    "passivo": "пассивный",
    "pastorale": "пасторальный",
    "paterno": "отцовский",
    "patologico": "патологический",
    "patrimoniale": "патримониальный",
    "patriottico": "патриотический",
    "pauroso": "пугливый",
    "peculiare": "своеобразный",
    "penale": "уголовный",
    "pensionabile": "пенсионный",
    "percepito": "воспринимаемый",
    "pericoloso": "опасный",
    "periodico": "периодический",
    "permanente": "постоянный",
    "permesso": "разрешённый",
    "personale": "личный",
    "perverso": "извращённый",
    "pesante": "тяжёлый",
    "pessimista": "пессимистичный",
    "petroliero": "нефтяной",
    "piacevole": "приятный",
    "pianificato": "запланированный",
    "piano": "тихий/мягкий",
    "piccolo": "маленький",
    "pilota": "пилотный",
    "piovoso": "дождливый",
    "piovoso": "дождливый",
    "poco": "маленький/немного",
    "poetico": "поэтический",
    "poliziesco": "полицейский",
    "politico": "политический",
    "pollution": "загрязняющий",
    "polmonare": "лёгочный",
    "ponderoso": "весомый",
    "popolare": "популярный/народный",
    "popoloso": "многонаселённый",
    "portante": "несущий",
    "portoghese": "португальский",
    "posizionale": "позиционный",
    "positivo": "положительный",
    "possibile": "возможный",
    "possessivo": "притяжательный",
    "posteriore": "задний",
    "postumo": "посмертный",
    "potente": "могущественный",
    "potenziale": "потенциальный",
    "pratico": "практический",
    "preciso": "точный",
    "precluso": "закрытый/исключённый",
    "prediletto": "любимый",
    "pregante": "молящий",
    "pregevole": "ценный",
    "premuroso": "заботливый",
    "preparato": "подготовленный",
    "presentabile": "презентабельный",
    "presente": "настоящий/присутствующий",
    "presidenziale": "президентский",
    "presunto": "предполагаемый",
    "previsto": "предусмотренный",
    "prezioso": "драгоценный",
    "prima": "первый",
    "primario": "первичный",
    "primitivo": "примитивный",
    "principale": "главный",
    "privato": "частный",
    "probabile": "вероятный",
    "problematico": "проблематичный",
    "produttivo": "продуктивный",
    "professionale": "профессиональный",
    "profondo": "глубокий",
    "progressivo": "прогрессивный",
    "proibito": "запрещённый",
    "promettente": "многообещающий",
    "promosso": "продвинутый",
    "pronunciato": "произнесённый",
    "propizio": "благоприятный",
    "proporzionale": "пропорциональный",
    "proprio": "собственный",
    "proposito": "целенаправленный",
    "prossimale": "проксимальный",
    "prossimo": "ближайший",
    "protetto": "защищённый",
    "protestante": "протестантский",
    "provinciale": "провинциальный",
    "provvisto": "снабжённый",
    "prudente": "осторожный/благоразумный",
    "pubblico": "общественный",
    "punteruolo": "остроконечный",
    "puro": "чистый",
    "push": "толкающий",
    "qualificato": "квалифицированный",
    "qualunque": "любой",
    "quindicinale": "двухнедельный",
    "quotidiano": "ежедневный",
    "radicale": "радикальный",
    "radioattivo": "радиоактивный",
    "ragionevole": "разумный",
    "rapido": "быстрый",
    "raro": "редкий",
    "razionale": "рациональный",
    "reale": "реальный/королевский",
    "recente": "недавний",
    "reciproco": "взаимный",
    "recuperabile": "восстановимый",
    "redazionale": "редакционный",
    "referendum": "референдумный",
    "regionale": "региональный",
    "regolare": "регулярный",
    "relativo": "относительный",
    "relegato": "отправленный в ссылку",
    "reliquiale": "реликварный",
    "remoto": "отдалённый",
    "renitente": "непокорный",
    "responsabile": "ответственный",
    "restante": "оставшийся",
    "restio": "недовольный",
    "restituito": "возвращённый",
    "restringente": "суживающий",
    "retroattivo": "обратнодействующий",
    "retrospettivo": "ретроспективный",
    "riassorbito": "впитанный",
    "ribelle": "мятежный",
    "ricco": "богатый",
    "ricercato": "разыскиваемый",
    "ricettivo": "рецептивный",
    "richiesto": "запрошенный",
    "riconosciuto": "признанный",
    "ricorrente": "повторяющийся",
    "ricorsivo": "рекурсивный",
    "ridotto": "уменьшенный",
    "riempito": "наполненный",
    "rifiutato": "отвергнутый",
    "rilevante": "значительный",
    "rilevato": "обнаруженный",
    "riluttante": "неохотный",
    "riminato": "осуждённый",
    "rinomato": "прославленный",
    "rinvenuto": "обнаруженный",
    "riparatore": "ремонтный",
    "ripetitivo": "повторяющийся",
    "ripido": "крутой",
    "riportato": "доставленный",
    "riposante": "успокаивающий",
    "ripreso": "возобновлённый",
    "riproduttivo": "репродуктивный",
    "riscontrato": "выявленный",
    "riservato": "зарезервированный",
    "risibile": "смешной/смехотворный",
    "risolto": "решённый",
    "rispettabile": "уважаемый",
    "rispettivo": "соответствующий",
    "rispettoso": "почтительный",
    "rispondente": "отвечающий",
    "risultante": "результирующий",
    "risultato": "полученный в результате",
    "ritenuto": "считаемый",
    "ritirato": "отозванный",
    "ritoccato": "подправленный",
    "ritrovato": "найденный",
    "riveniente": "прибывающий",
    "robotico": "роботизированный",
    "romano": "римский",
    "romantico": "романтический",
    "rotondo": "круглый",
    "rosso": "красный",
    "rovinaio": "разрушительный",
    "rovinoso": "разрушительный",
    "rubato": "украденный",
    "rurale": "сельский",
    "rustico": "деревенский",
    "sacrificato": "принесённый в жертву",
    "sacro": "священный",
    "saggio": "мудрый",
    "salubre": "здоровый",
    "salvaggio": "дикий",
    "salvifico": "спасительный",
    "sano": "здоровый",
    "santo": "святой",
    "sapiens": "разумный",
    "sardo": "сардинский",
    "saziante": "насыщающий",
    "scadente": "низкокачественный",
    "scarsamente": "скудный",
    "scarso": "скудный/недостаточный",
    "scatenato": "развязанный",
    "scandaloso": "скандальный",
    "scapito": "ущербный",
    "scars": "скудный",
    "scenografico": "сценографический",
    "scettico": "скептический",
    "schietto": "искренний",
    "scientifico": "научный",
    "scolastico": "школьный",
    "scomodo": "неудобный",
    "scomunicato": "отлучённый",
    "sconnesso": "разрозненный",
    "sconosciuto": "неизвестный",
    "scostante": "неприветливый",
    "scout": "разведывательный",
    "scaduto": "просроченный",
    "scritturale": "письменный",
    "scuro": "тёмный",
    "sdraiato": "лёжащий",
    "secolare": "вековой",
    "sedentario": "сидячий",
    "sedizioso": "мятежный",
    "segnalato": "отмеченный",
    "segreto": "секретный",
    "seguente": "следующий",
    "selezionato": "выбранный",
    "semantico": "семантический",
    "sembiante": "похожий",
    "sensibile": "чувствительный",
    "sensoriale": "сенсорный",
    "sentimentale": "сентиментальный",
    "separato": "отдельный",
    "sepolcrale": "могильный",
    "sequenziale": "последовательный",
    "serio": "серьёзный",
    "serpentino": "змеиный",
    "servile": "рабский",
    "servizio": "служебный",
    "sessuale": "сексуальный",
    "severo": "строгий",
    "siciliano": "сицилийский",
    "silenzioso": "тихий/молчаливый",
    "silvestre": "лесной",
    "simbolico": "символический",
    "simile": "подобный",
    "simmetrico": "симметричный",
    "simpatico": "милый/симпатичный",
    "simultaneo": "одновременный",
    "sinistro": "левый/зловещий",
    "sintetico": "синтетический",
    "sistematico": "систематический",
    "sociale": "социальный",
    "soccorrevole": "помогающий",
    "soffice": "мягкий/пушистый",
    "soffrente": "страдающий",
    "sovrano": "суверенный",
    "sovrapposto": "наложенный",
    "spaccone": "хвастливый",
    "spaziale": "пространственный",
    "spazio": "пространственный",
    "speciale": "особый",
    "speciale": "особый",
    "specifico": "конкретный",
    "spettacolare": "зрелищный",
    "spietato": "безжалостный",
    "spinoso": "колючий",
    "spirituale": "духовный",
    "splendido": "великолепный",
    "spontaneo": "спонтанный",
    "sportivo": "спортивный",
    "sprecato": "потраченный впустую",
    "spronato": "подстёгнутый",
    "sproporzionato": "непропорциональный",
    "spurio": "ложный/поддельный",
    "squadrista": "военизированный",
    "stabile": "стабильный",
    "stabile": "стабильный",
    "staccato": "отдельный/отрывистый",
    "stagionale": "сезонный",
    "stagnante": "застойный",
    "statico": "статический",
    "statistico": "статистический",
    "stradale": "дорожный",
    "straniero": "иностранный",
    "straordinario": "экстраординарный",
    "strappato": "порванный",
    "strettamente": "строгий",
    "stretto": "узкий/тесный",
    "strutturale": "структурный",
    "studiato": "изученный",
    "stupendo": "потрясающий",
    "subacqueo": "подводный",
    "subentrante": "вступающий",
    "subissato": "заваленный",
    "sublime": "возвышенный",
    "subordinato": "подчинённый",
    "successivo": "последующий",
    "sufficiente": "достаточный",
    "suggestivo": "выразительный",
    "suicida": "самоубийственный",
    "sunto": "краткий",
    "superbo": "надменный",
    "superficiale": "поверхностный",
    "superiore": "высший/верхний",
    "supplementare": "дополнительный",
    "sopportabile": "терпимый",
    "sopportato": "вынесенный",
    "soprannaturale": "сверхъестественный",
    "soprano": "верхний",
    "sopravvissuto": "выживший",
    "sostenibile": "устойчивый",
    "sostenuto": "поддержанный",
    "sospetto": "подозрительный",
    "sospeso": "приостановленный",
    "sostituito": "заменённый",
    "sostitutivo": "заменительный",
    "sottile": "тонкий",
    "sottinteso": "подразумеваемый",
    "sottomesso": "покорный",
    "sottostante": "нижележащий",
    "sottoterra": "подземный",
    "sovietico": "советский",
    "sovrammentale": "сверхментальный",
    "sovranazionale": "наднациональный",
    "spaventoso": "страшный",
    "spaventato": "испуганный",
    "spento": "потухший",
    "sperduto": "затерянный",
    "sperimentale": "экспериментальный",
    "sperone": "шпоровый",
    "spesso": "частый",
    "spezzato": "сломанный",
    "torinese": "туринский",
    "tossico": "токсичный",
    "tradizionale": "традиционный",
    "tragico": "трагический",
    "tranquillo": "спокойный",
    "trasformato": "преобразованный",
    "trasparente": "прозрачный",
    "trasparente": "прозрачный",
    "trattenuto": "сдержанный",
    "tremendo": "ужасный",
    "tricolore": "трёхцветный",
    "triste": "грустный",
    "trionfale": "триумфальный",
    "trito": "банальный",
    "truccato": "накрашенный",
    "tumultuoso": "бурный",
    "tunisino": "тунисский",
    "turistico": "туристический",
    "tutto": "весь/целый",
    "ubbidiente": "послушный",
    "ufficiale": "официальный",
    "ufficiale": "официальный",
    "uguale": "равный",
    "ultimativo": "ультимативный",
    "umano": "человеческий",
    "umile": "скромный",
    "umiliante": "унизительный",
    "unanime": "единогласный",
    "unico": "единственный",
    "unilaterale": "односторонний",
    "unisono": "унисон",
    "unitario": "унитарный",
    "universale": "универсальный",
    "universitario": "университетский",
    "inguaribile": "неизлечимый",
    "innamorato": "влюблённый",
    "inverno": "зимний",
    "inveso": "израненный",
    "invincibile": "непобедимый",
    "violento": "насильственный",
    "virtuoso": "добродетельный",
    "violato": "нарушенный",
    "vissuto": "прожитый",
    "vitale": "жизненный",
    "vitello": "телячий",
    "vivente": "живой",
    "visibile": "видимый",
    "visionario": "визионерский",
    "viscido": "липкий",
    "virtuale": "виртуальный",
    "violaceo": "фиолетовый",
    "vinto": "побеждённый",
    "vincolante": "обязывающий",
    "vincitore": "победный",
    "villoso": "волосатый",
    "vigente": "действующий",
    "video": "видео",
    "vibrante": "вибрирующий",
    "vibrato": "дрожащий",
    "vergognoso": "стыдливый",
    "veneto": "венетский",
    "velato": "завуалированный",
    "veemente": "страстный",
    "vantaggioso": "выгодный",
    "vanitoso": "тщеславный",
    "valutario": "оценочный",
    "valido": "действительный",
    "vago": "смутный",
    "vacillante": "шатающийся",
    "vabene": "хороший",
    "utz": "хороший",
    "wrangler": "ковбойский",
    "zac": "острый",
    "zen": "дзен",
    "zingaresco": "цыганский",
    "zonale": "зональный",
    "zoppo": "хромой",
    "zotico": "грубый/невежа",
    "audace": "смелый",
    "avventuroso": "приключенческий",
    "azzurro": "голубой",
    "basilare": "базовый",
    "battuto": "битый",
    "benigno": "доброкачественный",
    "benestante": "состоятельный",
    "benche": "хотя",
    "big": "большой (англ.)",
    "biografico": "биографический",
    "bizzarro": "странный",
    "bonario": "добродушный",
    "borghese": "буржуазный",
    "burocratico": "бюрократический",
    "caduto": "упавший",
    "cancellato": "отменённый",
    "candidato": "кандидатский",
    "canonico": "канонический",
    "cantato": "спетый",
    "capace": "способный",
    "capillare": "капиллярный",
    "captato": "уловленный",
    "caratteristico": "характерный",
    "carismatico": "харизматичный",
    "carnale": "плотский",
    "caro": "дорогой",
    "carolingio": "каролингский",
    "cattolico": "католический",
    "causale": "причинный",
    "celebrativo": "торжественный",
    "centenario": "столетний",
    "cerebrale": "мозговой",
    "certo": "уверенный",
    "chiaro": "ясный",
    "chilometrico": "километровый",
    "cimiteriale": "кладбищенский",
    "cinese": "китайский",
    "cinico": "циничный",
    "cinquecentesco": "шестнадцатый век",
    "circonstanziale": "обстоятельственный",
    "civettardo": "кокетливый",
    "clandestino": "тайный/нелегальный",
    "classico": "классический",
    "claustrale": "клаустрофобический",
    "climatico": "климатический",
    "clinico": "клинический",
    "cognitivo": "когнитивный",
    "collettivo": "коллективный",
    "collinare": "холмистый",
    "collocato": "размещённый",
    "colombiano": "колумбийский",
    "colorato": "цветной",
    "comandante": "командующий",
    "combinato": "комбинированный",
    "comico": "комический",
    "commerciale": "коммерческий",
    "commovente": "трогательный",
    "commestibile": "съедобный",
    "comparabile": "сравнимый",
    "compatibile": "совместимый",
    "competitivo": "конкурентоспособный",
    "complesso": "сложный",
    "compiuto": "завершённый",
    "composto": "составной",
    "compresso": "сжатый",
    "comprensibile": "понятный",
    "comprensivo": "понимающий",
    "comprensivo": "включающий",
    "compromettente": "компрометирующий",
    "comune": "общий/обычный",
    "comunitario": "общинный",
    "concepire": "зачаточный",
    "concettuale": "концептуальный",
    "conclusivo": "заключительный",
    "concreto": "конкретный",
    "condizionale": "условный",
    "condotto": "проведённый",
    "confessionale": "конфессиональный",
    "confermato": "подтверждённый",
    "confinante": "соседний/граничащий",
    "confortevole": "уютный",
    "congenito": "врождённый",
    "congiuntivo": "сослагательный",
    "connesso": "связанный",
    "conquistato": "завоёванный",
    "consacrato": "освящённый",
    "consegnato": "доставленный",
    "conseguente": "следующий/последующий",
    "consensuale": "согласованный",
    "conservativo": "консервативный",
    "considerevole": "значительный",
    "consistente": "значительный",
    "consueto": "обычный",
    "consultivo": "консультативный",
    "consumato": "совершённый",
    "contabile": "счётный",
    "contadino": "крестьянский",
    "contemporaneo": "современный",
    "contenibile": "сдерживаемый",
    "contenuto": "сдержанный",
    "conteso": "оспариваемый",
    "continentale": "континентальный",
    "continuo": "непрерывный",
    "contraddittorio": "противоречивый",
    "contrario": "противоположный",
    "contratto": "сжатый",
    "contrattuale": "договорной",
    "contraente": "заключающий",
    "contributivo": "взносный",
    "controverso": "спорный",
    "conveniente": "удобный/выгодный",
    "convenzionale": "условный",
    "convergente": "сходящийся",
    "convinto": "убеждённый",
    "cooperativo": "кооперативный",
    "coreografico": "хореографический",
    "corporativo": "корпоративный",
    "corpulento": "тучный",
    "correlativo": "коррелятивный",
    "corrente": "текущий",
    "corretto": "правильный",
    "corrodibile": "разъедаемый",
    "corrotto": "коррумпированный",
    "cortese": "вежливый",
    "cortigiano": "придворный",
    "cosciente": "сознающий",
    "cosmico": "космический",
    "cosmopolita": "космополитичный",
    "costiero": "прибрежный",
    "costituzionale": "конституционный",
    "costoso": "дорогой",
    "cotidian": "ежедневный",
    "creativo": "творческий",
    "cresciuto": "выросший",
    "criminale": "преступный",
    "criminogeno": "криминогенный",
    "crudele": "жестокий",
    "culturale": "культурный",
    "curato": "курированный",
    "curioso": "любопытный",
    "da": "от",
    "dannoso": "вредный",
    "decorrente": "текущий",
    "degenerato": "выродившийся",
    "degno": "достойный",
    "delittuoso": "преступный",
    "demenziale": "слабоумный",
    "democratico": "демократический",
    "demoniaco": "демонический",
    "denso": "плотный/густой",
    "dental": "зубной",
    "dentato": "зубчатый",
    "depressivo": "депрессивный",
    "derivato": "производный",
    "descrittivo": "описательный",
    "desunto": "выведенный",
    "determinante": "определяющий",
    "determinativo": "определительный",
    "devastante": "разрушительный",
    "devoto": "преданный/набожный",
    "didattico": "дидактический",
    "dietrologico": "конспирологический",
    "differente": "отличный",
    "differito": "отложенный",
    "diffidente": "недоверчивый",
    "difficile": "трудный",
    "diffusamente": "распространённый",
    "diffuso": "распространённый",
    "digitale": "цифровой",
    "dignitoso": "достойный",
    "dimenticato": "забытый",
    "dimostrativo": "демонстративный",
    "dimostrato": "доказанный",
    "dinamico": "динамичный",
    "dipendente": "зависимый",
    "diplomatico": "дипломатический",
    "diretto": "прямой",
    "dirigenziale": "руководящий",
    "dirimente": "разрешающий",
    "disabilitante": "инвалидизирующий",
    "disastroso": "катастрофический",
    "dischetto": "дисковый",
    "discretamente": "достаточно",
    "discreto": "дискретный",
    "discusso": "обсуждённый",
    "disdegnoso": "презрительный",
    "disgiunto": "разделённый",
    "disilluso": "разочарованный",
    "disperato": "отчаянный",
    "disponibile": "доступный",
    "disposto": "расположенный",
    "disputato": "оспариваемый",
    "disteso": "растянутый",
    "distintivo": "отличительный",
    "distribuito": "распределённый",
    "disturbato": "потревоженный",
    "divenuto": "ставший",
    "diverso": "разный",
    "divino": "божественный",
    "divisionale": "дивизионный",
    "dolorante": "болезненный",
    "doloroso": "болезненный",
    "domestico": "домашний",
    "dominante": "господствующий",
    "donato": "подаренный",
    "dormiente": "спящий",
    "dorato": "золотистый",
    "dottorale": "докторский",
    "drammatico": "драматический",
    "dubitativo": "сомнительный",
    "duraturo": "долговечный",
    "ebreo": "еврейский",
    "eccezionale": "исключительный",
    "ecologico": "экологический",
    "economico": "экономический",
    "edile": "строительный",
    "editoriale": "редакционный",
    "effettivo": "фактический",
    "efficace": "эффективный",
    "egiziano": "египетский",
    "elaborato": "разработанный",
    "elargito": "пожалованный",
    "elettivo": "выборный",
    "elettrico": "электрический",
    "elettronico": "электронный",
    "elegante": "элегантный",
    "elementare": "элементарный",
    "elevato": "возвышенный",
    "eliminato": "устранённый",
    "elite": "элитный",
    "elogioso": "хвалебный",
    "emarginato": "маргинальный",
    "emergente": "новый/восходящий",
    "emotivo": "эмоциональный",
    "empirico": "эмпирический",
    "enorme": "огромный",
    "epico": "эпический",
    "epocale": "эпохальный",
    "equo": "справедливый",
    "eroso": "разъеденный",
    "esaltante": "возвышающий",
    "esanime": "бескровный",
    "esasperato": "exasперированный",
    "esclusivo": "исключительный",
    "esecutivo": "исполнительный",
    "esente": "освобождённый",
    "esigente": "требовательный",
    "esilarante": "уморительный",
    "esistente": "существующий",
    "esitante": "колеблющийся",
    "esotico": "экзотический",
    "esoterico": "эзотерический",
    "esplicito": "явный",
    "esposto": "выставленный",
    "espressivo": "выразительный",
    "espulso": "высланный",
    "essenziale": "существенный",
    "estasiato": "восхищённый",
    "estensibile": "расширяемый",
    "estetico": "эстетический",
    "estraneo": "чужой",
    "europeo": "европейский",
    "evolutivo": "эволюционный",
    "faceto": "шутливый",
    "fallimentare": "провальный",
    "famoso": "знаменитый",
    "familiare": "семейный",
    "fantastico": "фантастический",
    "fantomatico": "таинственный",
    "faraonico": "фараонов",
    "farmacologico": "фармакологический",
    "fascinoso": "обаятельный",
    "fastidioso": "надоедливый",
    "fatale": "роковой",
    "fattibile": "выполнимый",
    "fattuale": "фактический",
    "favoloso": "сказочный",
    "fecondo": "плодородный",
    "federale": "федеральный",
    "femminile": "женский",
    "femminista": "феминистский",
    "fenomenale": "феноменальный",
    "feudale": "феодальный",
    "fidato": "надёжный",
    "fiducioso": "уверенный",
    "filiale": "дочерний",
    "filosofico": "философский",
    "finanziario": "финансовый",
    "finale": "финальный",
    "finto": "поддельный",
    "firmato": "подписанный",
    "fiscale": "налоговый",
    "fisico": "физический",
    "fittizio": "вымышленный",
    "flessibile": "гибкий",
    "fluviale": "речной",
    "folkloristico": "фольклорный",
    "folle": "безумный",
    "fondamentale": "основной",
    "fondato": "обоснованный",
    "fonetico": "фонетический",
    "forestale": "лесной",
    "formale": "формальный",
    "formidabile": "грозный",
    "fornito": "снабжённый",
    "fortificato": "укреплённый",
    "fortunato": "удачливый",
    "forzato": "принудительный",
    "fotogenico": "фотогеничный",
    "fotografico": "фотографический",
    "fraterno": "братский",
    "frequente": "частый",
    "fresco": "свежий",
    "frontale": "фронтальный",
    "fruttuoso": "плодотворный",
    "fuori": "наружный",
    "fuoriuscito": "эмигрировавший",
    "furbo": "хитрый",
    "futuribile": "возможный в будущем",
    "gadget": "гаджетный",
    "galattico": "галактический",
    "galleggiante": "плавающий",
    "garantito": "гарантированный",
    "garbato": "учтивый",
    "gassoso": "газообразный",
    "gaudi": "гаудиевый",
    "generazionale": "поколенческий",
    "generico": "общий",
    "genetico": "генетический",
    "geniale": "гениальный",
    "gentile": "любезный",
    "genuino": "искренний",
    "gerarchico": "иерархический",
    "germanico": "германский",
    "gestito": "управляемый",
    "gigante": "гигантский",
    "gigantesco": "гигантский",
    "giornalistico": "журналистский",
    "giovane": "молодой",
    "giovanile": "юношеский",
    "giudiziario": "судебный",
    "giuridico": "юридический",
    "globale": "глобальный",
    "glorioso": "славный",
    "gotico": "готический",
    "governativo": "правительственный",
    "graduale": "постепенный",
    "grande": "большой",
    "grasso": "жирный",
    "gratificante": "благодарный",
    "gratuito": "бесплатный",
    "grave": "тяжёлый",
    "gratoso": "признательный",
    "gratos": "признательный",
    "grosso": "большой",
    "guadagnato": "заработанный",
    "guarito": "исцелённый",
    "guasto": "сломанный",
    "guerriero": "воинственный",
    "iconico": "культовый",
    "identico": "идентичный",
    "ideologico": "идеологический",
    "illuminato": "просвещённый",
    "illustre": "иллюстрирующий",
    "immaginario": "воображаемый",
    "immacolato": "непорочный",
    "immediato": "непосредственный",
    "immobile": "недвижимый",
    "immunologico": "иммунологический",
    "imparziale": "беспристрастный",
    "impegnativo": "обязывающий",
    "imperativo": "повелительный",
    "imperiale": "имперский",
    "impermeabile": "водонепроницаемый",
    "implacabile": "неумолимый",
    "implicito": "подразумеваемый",
    "imponente": "внушительный",
    "importante": "важный",
    "impossibile": "невозможный",
    "impotente": "бессильный",
    "impreciso": "неточный",
    "imprevedibile": "непредсказуемый",
    "imprevisto": "непредвиденный",
    "improprio": "несоответствующий",
    "improvviso": "внезапный",
    "imputato": "обвиняемый",
    "inadeguato": "недостаточный",
    "inaccettabile": "неприемлемый",
    "inatteso": "неожиданный",
    "incalcolabile": "неисчислимый",
    "incapace": "неспособный",
    "incarcerato": "заключённый",
    "incarnato": "воплощённый",
    "incerto": "неуверенный",
    "inclusivo": "включающий",
    "incolpevole": "невиновный",
    "incompiuto": "незавершённый",
    "inconsapevole": "несознательный",
    "incontenibile": "неудержимый",
    "inconveniente": "неудобный",
    "incorporato": "встроенный",
    "incorruttibile": "некоррумпируемый",
    "incredibile": "невероятный",
    "incriminato": "обвинённый",
    "incrociato": "скрещённый",
    "indeterminato": "неопределённый",
    "indifferente": "безразличный",
    "indipendente": "независимый",
    "indiretto": "косвенный",
    "indispensabile": "незаменимый",
    "indistinto": "неразличимый",
    "individuale": "индивидуальный",
    "indiziario": "уликовый",
    "indotto": "побуждённый",
    "industriale": "промышленный",
    "inebriante": "опьяняющий",
    "inefficace": "неэффективный",
    "inefficiente": "неэффективный",
    "ineguagliabile": "несравненный",
    "ineludibile": "неизбежный",
    "inesperto": "неопытный",
    "inespugnabile": "неприступный",
    "inetto": "неспособный",
    "inevitabile": "неизбежный",
    "infantile": "детский",
    "infastidito": "раздражённый",
    "infernale": "адский",
    "infido": "коварный",
    "infinito": "бесконечный",
    "inflazionato": "инфляционный",
    "influente": "влиятельный",
    "informale": "неформальный",
    "informato": "информированный",
    "informativo": "информативный",
    "infranto": "разбитый",
    "infruttuoso": "бесплодный",
    "ingiusto": "несправедливый",
    "ingiurioso": "оскорбительный",
    "inglese": "английский",
    "ingombrante": "громоздкий",
    "innaturale": "неестественный",
    "innegabile": "неоспоримый",
    "innocente": "невинный",
    "innovativo": "новаторский",
    "innumerevole": "бесчисленный",
    "inquietante": "тревожный",
    "inquieto": "беспокойный",
    "insalubre": "нездоровый",
    "insanguinato": "окровавленный",
    "insicuro": "неуверенный",
    "insistente": "настоятельный",
    "insolito": "необычный",
    "insonne": "бессонный",
    "insopportabile": "невыносимый",
    "insospettato": "неожиданный",
    "insufficiente": "недостаточный",
    "insulso": "безвкусный",
    "intatto": "нетронутый",
    "integrale": "интегральный",
    "intellettuale": "интеллектуальный",
    "intelligente": "умный",
    "intenso": "интенсивный",
    "intenzionale": "намеренный",
    "interattivo": "интерактивный",
    "interessante": "интересный",
    "interiore": "внутренний",
    "intero": "целый",
    "interpersonale": "межличностный",
    "intimo": "интимный",
    "intoccabile": "неприкасаемый",
    "intrattenibile": "неудержимый",
    "intricato": "запутанный",
    "intriso": "пропитанный",
    "intriso": "пропитанный",
    "intriso": "пропитанный",
    "intronato": "оглушённый",
    "intuitivo": "интуитивный",
    "inutile": "бесполезный",
    "invaso": "вторгшийся",
    "invasivo": "инвазивный",
    "invecente": "ругающий",
    "invernale": "зимний",
    "inverso": "обратный",
    "investigativo": "следственный",
    "inviso": "ненавистный",
    "invisibile": "невидимый",
    "involontario": "непроизвольный",
    "involto": "завёрнутый",
    "ironico": "ироничный",
    "irrazionale": "иррациональный",
    "irreale": "нереальный",
    "irreparabile": "непоправимый",
    "irreprensibile": "безупречный",
    "irresistibile": "неотразимый",
    "irresponsabile": "безответственный",
    "irreversibile": "необратимый",
    "irrigidito": "одеревеневший",
    "irrinunciabile": "неотъемлемый",
    "ispanico": "испанский",
    "isolato": "изолированный",
    "italiano": "итальянский",
    "iterativo": "повторяющийся",
    "lampante": "очевидный",
    "laureato": "выпускник",
    "lavato": "вымытый",
    "legale": "законный",
    "leggibile": "читаемый",
    "leggero": "лёгкий",
    "legittimo": "законный",
    "letale": "смертельный",
    "letterale": "буквальный",
    "letterario": "литературный",
    "leale": "верный",
    "libertario": "либертарный",
    "libero": "свободный",
    "libresco": "книжный",
    "limitato": "ограниченный",
    "lineare": "линейный",
    "linguistico": "языковой",
    "liquido": "жидкий",
    "listato": "перечисленный",
    "locale": "местный",
    "logico": "логический",
    "logistico": "логистический",
    "lombardo": "ломбардский",
    "lontano": "далёкий",
    "lordo": "грязный/брутто",
    "luminoso": "светлый",
    "lungo": "длинный",
    "lusso": "роскошный",
    "macabro": "мрачный",
    "macchinico": "машинный",
    "madornale": "грубый/серьёзный",
    "maggiorenne": "совершеннолетний",
    "magico": "магический",
    "magnetico": "магнитный",
    "magnifico": "великолепный",
    "magro": "худой",
    "maiestoso": "величественный",
    "majorento": "больший",
    "malsano": "нездоровый",
    "mammifero": "млекопитающий",
    "manovrabile": "управляемый",
    "mansueto": "кроткий",
    "mantenuto": "содержимый",
    "manuale": "ручной",
    "mappato": "картированный",
    "marcatamente": "отмеченный",
    "marinaresco": "морской",
    "marittimo": "морской",
    "marsigliese": "марсельский",
    "martirizzato": "замученный",
    "maschile": "мужской",
    "massacrato": "перебитый",
    "massiccio": "массивный",
    "massimalista": "максимальный",
    "matematico": "математический",
    "materiale": "материальный",
    "materno": "материнский",
    "matrimoniale": "брачный",
    "maturo": "зрелый",
    "meccanico": "механический",
    "medesimo": "тот же",
    "medico": "медицинский",
    "medievale": "средневековый",
    "medio": "средний",
    "melodico": "мелодичный",
    "memorabile": "запоминающийся",
    "mendace": "лживый",
    "menzognero": "лживый",
    "meraviglioso": "удивительный",
    "meridionale": "южный",
    "messo": "посланный",
    "metallifero": "металлоносный",
    "metropolitano": "столичный",
    "militare": "военный",
    "militante": "боевой/действующий",
    "millenario": "тысячелетний",
    "minacciato": "угрожаемый",
    "minacciato": "угрожаемый",
    "minore": "младший/меньший",
    "minorenne": "несовершеннолетний",
    "mirabile": "удивительный",
    "miracoloso": "чудесный",
    "misurabile": "измеримый",
    "misterioso": "таинственный",
    "mite": "мягкий/нежный",
    "mitico": "мифический",
    "mobiliare": "движимый",
    "moderno": "современный",
    "modesto": "скромный",
    "modificato": "изменённый",
    "mondiale": "мировой",
    "monopolistico": "монопольный",
    "monumentale": "монументальный",
    "morale": "нравственный",
    "morbido": "мягкий",
    "mordi": "кусающий",
    "mortale": "смертный",
    "mosso": "движущийся",
    "motivato": "мотивированный",
    "motorio": "моторный",
    "movimentato": "оживлённый",
    "muliebre": "женский",
    "municipale": "муниципальный",
    "musicale": "музыкальный",
    "mutevole": "изменчивый",
    "muto": "немой",
    "nazionale": "национальный",
    "necessario": "необходимый",
    "necrologico": "некрологический",
    "negativo": "отрицательный",
    "neocapitalista": "неокапиталистический",
    "neoidealista": "неоидеалистический",
    "neroso": "мускулистый",
    "nervoso": "нервный",
    "neurale": "нейронный",
    "neutro": "нейтральный",
    "nichelato": "никелированный",
    "nobile": "благородный",
    "nocivo": "вредный",
    "noioso": "скучный",
    "nomade": "кочевой",
    "nominale": "номинальный",
    "nonno": "дедушкин",
    "nonostante": "несмотря на",
    "normale": "нормальный",
    "normativo": "нормативный",
    "nostro": "наш",
    "noto": "известный",
    "notturno": "ночной",
    "novello": "новый",
    "nucleare": "ядерный",
    "nudo": "голый",
    "numerico": "числовой",
    "numeroso": "многочисленный",
    "nutrito": "питательный",
    "obbediente": "послушный",
    "obbligatorio": "обязательный",
    "oggettivo": "объективный",
    "omicida": "убийственный",
    "onnipresente": "вездесущий",
    "onnisciente": "всеведущий",
    "operante": "действующий",
    "operativo": "оперативный",
    "opposto": "противоположный",
    "oppressivo": "гнетущий",
    "ottimale": "оптимальный",
    "ottimistico": "оптимистический",
    "pacifico": "мирный",
    "pagato": "оплаченный",
    "pagherò": "вексельный",
    "palazzo": "дворцовый",
    "palermitano": "палермитанский",
    "pallido": "бледный",
    "parallelo": "параллельный",
    "parentale": "семейный",
    "parlamentare": "парламентский",
    "parlato": "разговорный",
    "parziale": "частичный",
    "pascoliano": "паскалевский",
    "passivo": "пассивный",
    "pastorale": "пастырский",
    "paterno": "отцовский",
    "patologico": "патологический",
    "patriottico": "патриотический",
    "patrimoniale": "наследственный",
    "pauroso": "страшный",
    "peccaminoso": "греховный",
    "peculiare": "своеобразный",
    "pedagogico": "педагогический",
    "penale": "уголовный",
    "penetrante": "проникающий",
    "pensato": "задуманный",
    "pensieroso": "задумчивый",
    "percepito": "воспринятый",
    "percorribile": "проходимый",
    "perdente": "проигравший",
    "perfezionato": "усовершенствованный",
    "pericolante": "опасный",
    "pericoloso": "опасный",
    "periodico": "периодический",
    "permanente": "постоянный",
    "permesso": "разрешённый",
    "persiano": "персидский",
    "persistente": "стойкий",
    "personale": "личный",
    "personaggio": "персонажный",
    "persuasivo": "убедительный",
    "perverso": "извращённый",
    "pessimista": "пессимистичный",
    "pestifero": "вредный/надоедливый",
    "petrolchimico": "нефтехимический",
    "petrolio": "нефтяной",
    "piacevole": "приятный",
    "piano": "тихий",
    "piccolo": "маленький",
    "pilota": "пилотный",
    "pinzochero": "ханжеский",
    "pionieristico": "пионерский",
    "piovoso": "дождливый",
    "pisano": "пизанский",
    "plausibile": "правдоподобный",
    "plenario": "пленарный",
    "politico": "политический",
    "polluto": "загрязнённый",
    "polmonare": "лёгочный",
    "poliedrico": "многогранный",
    "popolare": "народный",
    "popoloso": "многонаселённый",
    "poroso": "пористый",
    "portante": "несущий",
    "portoghese": "португальский",
    "positivo": "положительный",
    "possibile": "возможный",
    "posteriore": "задний",
    "postumo": "посмертный",
    "potente": "могущественный",
    "potenziale": "потенциальный",
    "pratico": "практичный",
    "precaria": "шаткий",
    "preciso": "точный",
    "precluso": "исключённый",
    "predatorio": "хищнический",
    "prediletto": "любимый",
    "pregevole": "ценный",
    "prelibato": "лакомый",
    "premesso": "предпосланный",
    "preparato": "подготовленный",
    "presente": "настоящий",
    "presidenziale": "президентский",
    "presunto": "предполагаемый",
    "previsto": "ожидаемый",
    "prezioso": "драгоценный",
    "prevenuto": "предвзятый",
    "principale": "главный",
    "principesco": "княжеский",
    "privato": "частный",
    "probabile": "вероятный",
    "problematico": "проблематичный",
    "procedurale": "процессуальный",
    "processo": "процессный",
    "proclive": "склонный",
    "produttivo": "производительный",
    "professionale": "профессиональный",
    "profetico": "пророческий",
    "profondo": "глубокий",
    "profumato": "душистый",
    "proibito": "запрещённый",
    "promettente": "многообещающий",
    "promosso": "произведённый",
    "pronto": "готовый",
    "pronunciato": "выраженный",
    "proporzionale": "пропорциональный",
    "proprio": "собственный",
    "propositivo": "конструктивный",
    "prossimo": "ближайший",
    "protetto": "защищённый",
    "protocollare": "протокольный",
    "protestatario": "протестующий",
    "protesto": "протестный",
    "provinciale": "провинциальный",
    "provocatorio": "провокационный",
    "provveduto": "снабжённый",
    "prudente": "осторожный",
    "psichiatrico": "психиатрический",
    "psicologico": "психологический",
    "pubblico": "публичный",
    "pugliese": "апулийский",
    "puro": "чистый",
    "pusher": "толкач",
    "qualitativo": "качественный",
    "quanto": "сколький",
    "quattrocentesco": "кватрочентистский",
    "quotidiano": "ежедневный",
    "raccomandato": "рекомендованный",
    "radente": "скользящий",
    "radiante": "сияющий",
    "radicale": "радикальный",
    "raffinato": "утончённый",
    "ragguardevole": "значительный",
    "ragionevole": "разумный",
    "rallegrato": "обрадованный",
    "ramificato": "разветвлённый",
    "rapido": "быстрый",
    "rappresentativo": "представительный",
    "raro": "редкий",
    "rassegna": "ревю",
    "ratificato": "ратифицированный",
    "reale": "действительный",
    "recente": "недавний",
    "recensito": "рецензированный",
    "reciproco": "взаимный",
    "reclutato": "набранный",
    "record": "рекордный",
    "recuperabile": "восстановимый",
    "redazionale": "редакционный",
    "regionale": "региональный",
    "registrato": "зарегистрированный",
    "regolato": "регулируемый",
    "regolare": "регулярный",
    "relativo": "относительный",
    "relegato": "сосланный",
    "reliquiale": "реликварный",
    "rimarchevole": "примечательный",
    "rimasto": "оставшийся",
    "rimborsabile": "возмещаемый",
    "rinascimentale": "ренессансный",
    "rinato": "возрождённый",
    "rinvenuto": "обнаруженный",
    "riproduttivo": "репродуктивный",
    "rinnovato": "обновлённый",
    "riparato": "отремонтированный",
    "riportato": "сообщённый",
    "ripreso": "возобновлённый",
    "risibile": "смешной",
    "risolto": "разрешённый",
    "risorgimentale": "рисорджиментальный",
    "rispettato": "уважаемый",
    "rispettivo": "соответствующий",
    "rispettoso": "уважительный",
    "rispondente": "соответствующий",
    "risultato": "результирующий",
    "ritenuto": "считаемый",
    "ritirato": "отозванный",
    "ritrovato": "обретённый",
    "rivale": "соперник/соперничающий",
    "romano": "римский",
    "romantico": "романтический",
    "rovinoso": "разрушительный",
    "russo": "русский",
    "rurale": "сельский",
    "saggio": "мудрый",
    "salubre": "здоровый",
    "salvaggio": "дикий",
    "santo": "святой",
    "sardo": "сардинский",
    "saziante": "насыщающий",
    "sbandato": "растерянный",
    "scadente": "низкого качества",
    "scaduto": "просроченный",
    "scalzo": "босой",
    "scandinavo": "скандинавский",
    "scapito": "ущербный",
    "scarsamente": "скудно",
    "scarso": "скудный",
    "scatenato": "необузданный",
    "scandaloso": "скандальный",
    "scatenato": "разъярённый",
    "scettico": "скептический",
    "scolastico": "школьный",
    "scomunicato": "отлучённый",
    "sconosciuto": "неизвестный",
    "scoperto": "открытый",
    "scottante": "острый/жгучий",
    "scrutinato": "рассмотренный",
    "scuro": "тёмный",
    "sdegnato": "негодующий",
    "secolare": "вековой",
    "sedentario": "сидячий",
    "sedizioso": "мятежный",
    "segnalato": "отмеченный",
    "segreto": "секретный",
    "selezionato": "отобранный",
    "semantico": "семантический",
    "sensibile": "чувствительный",
    "sensoriale": "сенсорный",
    "sentimentale": "чувствительный",
    "separato": "отдельный",
    "sepolcrale": "могильный",
    "sequenziale": "последовательный",
    "serio": "серьёзный",
    "servile": "раболепный",
    "sessuale": "сексуальный",
    "severo": "строгий",
    "siciliano": "сицилийский",
    "sicuro": "уверенный",
    "silenzioso": "тихий",
    "silvestre": "лесной",
    "simbolico": "символический",
    "simmetrico": "симметричный",
    "simpatico": "симпатичный",
    "simultaneo": "одновременный",
    "sinistro": "зловещий",
    "sintetico": "синтетический",
    "sistemato": "устроенный",
    "sistematico": "систематический",
    "soccorrevole": "помогающий",
    "sociale": "социальный",
    "sofferente": "страдающий",
    "solare": "солнечный",
    "soldatesco": "солдафонский",
    "solenne": "торжественный",
    "solidale": "солидарный",
    "solitario": "одинокий",
    "solo": "одинокий/единственный",
    "sommerso": "затопленный",
    "sonoro": "звучный",
    "soprannaturale": "сверхъестественный",
    "soprano": "верхний",
    "sopravvissuto": "выживший",
    "sorrentino": "соррентийский",
    "sorriso": "улыбающийся",
    "sostenibile": "приемлемый",
    "sostenuto": "поддержанный",
    "sottile": "тонкий",
    "sottomesso": "покорный",
    "sottostante": "нижележащий",
    "sovrano": "суверенный",
    "spaccone": "хвастливый",
    "spagnolo": "испанский",
    "spaziale": "пространственный",
    "speciale": "особый",
    "specifico": "конкретный",
    "spettacolare": "зрелищный",
    "spietato": "безжалостный",
    "spinoso": "колючий",
    "spirituale": "духовный",
    "splendido": "великолепный",
    "spontaneo": "спонтанный",
    "sportivo": "спортивный",
    "spregevole": "презренный",
    "sproporzionato": "непропорциональный",
    "spurio": "фальшивый",
    "stabile": "стабильный",
    "staccato": "обрывистый",
    "stagionale": "сезонный",
    "stagnante": "застойный",
    "statico": "статичный",
    "statistico": "статистический",
    "sterminato": "бескрайний",
    "stilistico": "стилистический",
    "stinco": "мёртвый",
    "stizzito": "раздражённый",
    "stradale": "дорожный",
    "straniero": "иностранный",
    "straordinario": "чрезвычайный",
    "strappato": "сорванный",
    "stretto": "узкий",
    "strutturale": "структурный",
    "stupendo": "потрясающий",
    "subacqueo": "подводный",
    "sublime": "возвышенный",
    "subordinato": "подчинённый",
    "successivo": "последующий",
    "suddetto": "вышеупомянутый",
    "sufficiente": "достаточный",
    "suggerito": "предложенный",
    "suggestivo": "выразительный",
    "sufficientemente": "достаточно",
    "sommesso": "приглушённый",
    "sonnolento": "сонный",
    "sperduto": "заблудший",
    "spento": "угасший",
    "spiegato": "объяснённый",
    "spinto": "толкаемый",
    "spoglio": "голый/обнажённый",
    "sprecato": "расточённый",
    "spruzzato": "забрызганный",
    "squallido": "мрачный",
    "squassato": "потрясённый",
    "stanco": "усталый",
    "storiografico": "историографический",
    "stupefacente": "поразительный",
    "suicida": "самоубийственный",
    "sunto": "краткий",
    "superbo": "высокомерный",
    "superficiale": "поверхностный",
    "superiore": "высший",
    "supplementare": "дополнительный",
    "soprattutto": "преимущественный",
    "sostenitore": "поддерживающий",
    "sospeso": "приостановленный",
    "sospinto": "подталкиваемый",
    "sostenitore": "сторонник",
    "temuto": "страшимый",
    "teorico": "теоретический",
    "territoriale": "территориальный",
    "terribile": "ужасный",
    "terroristico": "террористический",
    "teso": "натянутый",
    "testardo": "упрямый",
    "timido": "робкий",
    "tollerante": "терпимый",
    "tossico": "ядовитый",
    "tradizionale": "традиционный",
    "tragico": "трагический",
    "tranquillo": "спокойный",
    "transitorio": "переходный",
    "trasandato": "неряшливый",
    "trascurato": "запущенный",
    "trasformato": "преобразованный",
    "trasparente": "прозрачный",
    "trasversale": "поперечный",
    "trattenuto": "сдержанный",
    "tremendo": "ужасный",
    "trentino": "трентинский",
    "triangolare": "треугольный",
    "tricolore": "трёхцветный",
    "trionfale": "триумфальный",
    "triste": "грустный",
    "trito": "избитый",
    "trionfante": "торжествующий",
    "troppo": "слишком",
    "tubicolare": "трубчатый",
    "tumultuoso": "бурный",
    "tunisino": "тунисский",
    "turistico": "туристический",
    "tutti": "все",
    "tutto": "весь",
    "uguale": "равный",
    "ultimo": "последний",
    "umano": "человеческий",
    "umile": "скромный",
    "umiliante": "унизительный",
    "umile": "скромный",
    "unanime": "единогласный",
    "unico": "единственный",
    "unificato": "объединённый",
    "uniforme": "однородный",
    "unitario": "единый",
    "universale": "универсальный",
    "universitario": "университетский",
    "urbanistico": "градостроительный",
    "urbano": "городской",
    "urgente": "срочный",
    "utilizzato": "использованный",
    "utile": "полезный",
    "vacuo": "пустой",
    "vago": "неопределённый",
    "valente": "умелый",
    "valido": "действительный",
    "vanitoso": "тщеславный",
    "vantaggioso": "выгодный",
    "variabile": "переменный",
    "variopinto": "разноцветный",
    "vasto": "обширный",
    "veggente": "провидческий",
    "veicolante": "транспортный",
    "velato": "прикрытый",
    "venatorio": "охотничий",
    "veneziano": "венецианский",
    "ventoso": "ветреный",
    "verace": "истинный",
    "verbale": "устный",
    "vergognoso": "стыдливый",
    "veritiero": "правдивый",
    "verosimile": "правдоподобный",
    "verticale": "вертикальный",
    "vescovile": "епископский",
    "vestito": "одетый",
    "veterano": "ветеранский",
    "vicino": "близкий",
    "vietato": "запрещённый",
    "vigente": "действующий",
    "vigoroso": "мощный",
    "violento": "жестокий",
    "violaceo": "фиолетовый",
    "violato": "нарушенный",
    "virale": "вирусный",
    "virile": "мужественный",
    "virtuale": "виртуальный",
    "virtuoso": "добродетельный",
    "visibile": "видимый",
    "visionario": "визионерский",
    "visitato": "посещённый",
    "visivo": "зрительный",
    "vissuto": "пережитый",
    "vistoso": "броский",
    "viscido": "липкий",
    "vitale": "жизненный",
    "vituperato": "порицаемый",
    "vivente": "живой",
    "vivido": "живой/яркий",
    "viziato": "испорченный",
    "vincolato": "связанный",
    "vincibile": "победимый",
    "violento": "насильственный",
    "volgare": "вульгарный",
    "volontario": "добровольный",
    "volubile": "непостоянный",
    "vorace": "прожорливый",
    "votato": "посвящённый",
    "vuoto": "пустой",
    "zac": "острый",
    "zelante": "усердный",
    "zen": "дзенский",
    "zoppo": "хромой",
    "zotico": "грубый",
    "wrangler": "ковбой",
}

# ─── ADVERBS ─────────────────────────────────────────────────────────────────

adv_translations = {
    "come": "как",
    "oh": "о",
    "perche": "почему/потому что",
    "beh": "ну/в общем",
    "allora": "тогда/итак",
    "piu": "более/больше",
    "quindi": "поэтому/следовательно",
    "gia": "уже",
    "via": "прочь/долой",
    "ecco": "вот",
    "sotto": "под/внизу",
    "fino": "до/вплоть до",
    "stasera": "сегодня вечером",
    "scusi": "извините",
    "dietro": "позади/сзади",
    "pure": "также/даже",
    "probabilmente": "вероятно",
    "sopra": "над/сверху",
    "davanti": "перед/впереди",
    "pero": "но/однако",
    "piuttosto": "довольно/скорее",
    "insomma": "в общем/впрочем",
    "finalmente": "наконец",
    "oltre": "кроме/за/далее",
    "circa": "около/приблизительно",
    "ovviamente": "очевидно",
    "soltanto": "только",
    "semplicemente": "просто",
    "veloce": "быстро",
    "cosi": "так/таким образом",
    "anzi": "напротив/скорее",
    "veramente": "действительно",
    "esattamente": "точно",
    "certamente": "конечно/непременно",
    "assolutamente": "абсолютно",
    "proprio": "именно/совсем",
    "praticamente": "практически",
    "comunque": "во всяком случае",
    "davvero": "действительно/правда",
    "esclusivamente": "исключительно",
    "effettivamente": "фактически",
    "naturalmente": "естественно",
    "ovvio": "очевидный",
    "forse": "может быть/возможно",
    "oggi": "сегодня",
    "ieri": "вчера",
    "domani": "завтра",
    "adesso": "сейчас/теперь",
    "sempre": "всегда",
    "mai": "никогда",
    "spesso": "часто",
    "qualche volta": "иногда",
    "raramente": "редко",
    "molto": "очень/много",
    "poco": "мало",
    "tanto": "так много/столько",
    "troppo": "слишком",
    "abbastanza": "достаточно",
    "quasi": "почти",
    "appena": "едва/только что",
    "ancora": "ещё",
    "bene": "хорошо",
    "male": "плохо",
    "subito": "сразу/немедленно",
    "presto": "скоро/быстро",
    "tardi": "поздно",
    "ora": "сейчас/теперь",
    "prima": "до/сначала",
    "dopo": "после/потом",
    "durante": "во время",
    "intanto": "тем временем",
    "frattanto": "тем временем",
    "nel frattempo": "тем временем",
    "lentamente": "медленно",
    "rapidamente": "быстро",
    "improvvisamente": "внезапно",
    "gradualmente": "постепенно",
    "recentemente": "недавно",
    "attualmente": "в настоящее время",
    "attentamente": "внимательно",
    "accuratamente": "тщательно",
    "facilmente": "легко",
    "difficilmente": "с трудом",
    "fortemente": "сильно",
    "leggermente": "слегка",
    "profondamente": "глубоко",
    "ampiamente": "широко",
    "specialmente": "особенно",
    "particolarmente": "в частности",
    "principalmente": "главным образом",
    "generalmente": "обычно/вообще",
    "normalmente": "обычно",
    "completamente": "полностью",
    "totalmente": "целиком",
    "esattamente": "точно",
    "precisamente": "в точности",
    "perfino": "даже",
    "nemmeno": "даже не",
    "neanche": "даже не",
    "neppure": "даже не",
    "ne": "ни/не",
    "anche": "также/тоже",
    "inoltre": "кроме того",
    "perciò": "поэтому",
    "cosicché": "так что",
    "pertanto": "следовательно",
    "altrimenti": "иначе",
    "piuttosto che": "скорее чем",
    "sebbene": "хотя",
    "benché": "хотя",
    "nonostante": "несмотря на",
    "tranne": "кроме",
    "eccetto": "за исключением",
    "invece": "вместо/напротив",
    "infatti": "на самом деле",
    "in realtà": "в действительности",
    "almeno": "по крайней мере",
    "al massimo": "максимум",
    "al più": "самое большее",
    "più o meno": "более или менее",
    "approssimativamente": "приблизительно",
    "circa": "около",
    "verso": "к/по направлению",
    "lungo": "вдоль",
    "attraverso": "через",
    "accanto": "рядом",
    "vicino": "близко",
    "lontano": "далеко",
    "dentro": "внутри",
    "fuori": "снаружи",
    "su": "на",
    "giù": "вниз",
    "qui": "здесь",
    "qua": "здесь/сюда",
    "là": "там",
    "laggiù": "вон там",
    "lassù": "вон там наверху",
    "dappertutto": "везде",
    "ovunque": "везде/куда бы ни",
    "da qualche parte": "где-то",
    "da nessuna parte": "никуда",
    "a destra": "направо",
    "a sinistra": "налево",
    "diritto": "прямо",
    "indietro": "назад",
    "avanti": "вперёд",
    "insieme": "вместе",
    "da solo": "один/сам",
    "volentieri": "охотно",
    "certo": "конечно",
    "sicuramente": "непременно",
    "senz'altro": "безусловно",
    "senza dubbio": "без сомнения",
    "infatti": "действительно",
    "certo": "конечно",
    "idiota": "по-идиотски",
    "sessualmente": "сексуально",
}

# ─── Build lookup with fallback ──────────────────────────────────────────────

# Read all entries to build a comprehensive manual dictionary
# We'll add missing words with intelligent guesses

noun_lookup = {}
verb_lookup = {}
adj_lookup = {}
adv_lookup = {}

for k, v in noun_translations.items():
    noun_lookup[k.lower()] = v
for k, v in verb_translations.items():
    verb_lookup[k.lower()] = v
for k, v in adj_translations.items():
    adj_lookup[k.lower()] = v
for k, v in adv_translations.items():
    adv_lookup[k.lower()] = v


def get_translation(pos, lemma, original, rank):
    """Get Russian translation for a word, with fallback."""
    lem = lemma.lower().strip()
    orig = original.lower().strip()

    if pos == "NOUN":
        if lem in noun_lookup:
            return noun_lookup[lem]
        if orig in noun_lookup:
            return noun_lookup[orig]
    elif pos == "VERB":
        if lem in verb_lookup:
            return verb_lookup[lem]
        if orig in verb_lookup:
            return verb_lookup[orig]
    elif pos == "ADJ":
        if lem in adj_lookup:
            return adj_lookup[lem]
        if orig in adj_lookup:
            return adj_lookup[orig]
    elif pos == "ADV":
        if lem in adv_lookup:
            return adv_lookup[lem]
        if orig in adv_lookup:
            return adv_lookup[orig]

    # Fallback: return the lemma with a marker
    return f"[{lemma}]"


# ─── Italian adjective agreement ─────────────────────────────────────────────

def adjective_forms(lemma):
    """Generate f.sg, m.pl, f.pl from m.sg lemma."""
    lem = lemma.strip()

    # Invariable patterns
    invariable_endings = [
        "ista", "ante", "ente", "ense", "ese", "ile",
    ]

    # Check for -e ending (two-form adjectives)
    if lem.endswith("e") and not any(lem.endswith(x) for x in ["ale", "ile", "ose", "are", "ere", "ire"]):
        # -e → -e (f.sg), -i (m.pl), -i (f.pl)
        return lem, lem, lem[:-1] + "i", lem[:-1] + "i"

    # Standard -o ending (four-form adjectives)
    if lem.endswith("o"):
        stem = lem[:-1]
        return lem, stem + "a", stem + "i", stem + "e"

    # -ista ending
    if lem.endswith("ista"):
        return lem, lem, lem[:-2] + "isti", lem[:-2] + "iste"

    # -co/-go endings sometimes change in plural but we keep it simple
    # Invariable: words not ending in -o or -e in typical pattern
    if lem.endswith("a") or lem.endswith("i") or lem.endswith("ù") or lem.endswith("ì"):
        return lem, lem, lem, lem

    # Default: treat as invariable
    return lem, lem, lem, lem


# ─── Write output files ──────────────────────────────────────────────────────

nouns = []
verbs = []
adjs = []
advs = []

for rank, original, lemma, pos in entries:
    ru = get_translation(pos, lemma, original, rank)

    if pos == "NOUN":
        nouns.append((rank, lemma, "", ru))
    elif pos == "VERB":
        verbs.append((rank, lemma, "", ru))
    elif pos == "ADJ":
        msg = lemma
        fsg, mpl, fpl = adjective_forms(lemma)[1:]
        adjs.append((rank, msg, fsg, mpl, fpl, "", ru))
    elif pos == "ADV":
        advs.append((rank, lemma, "", "", ru, ""))

# Write nouns
noun_path = os.path.join(BASE, "v2_new_nouns.csv")
with open(noun_path, "w", encoding="utf-8", newline="") as f:
    w = csv.writer(f)
    w.writerow(["rank", "noun", "collocations", "ru"])
    for row in nouns:
        w.writerow(row)
print(f"NOUNS: {len(nouns)} → {noun_path}")

# Write verbs
verb_path = os.path.join(BASE, "v2_new_verbs.csv")
with open(verb_path, "w", encoding="utf-8", newline="") as f:
    w = csv.writer(f)
    w.writerow(["rank", "verb", "collocations", "ru"])
    for row in verbs:
        w.writerow(row)
print(f"VERBS: {len(verbs)} → {verb_path}")

# Write adjectives
adj_path = os.path.join(BASE, "v2_new_adjectives.csv")
with open(adj_path, "w", encoding="utf-8", newline="") as f:
    w = csv.writer(f)
    w.writerow(["rank", "adjective", "msg", "fsg", "mpl", "fpl", "collocations", "ru"])
    for row in adjs:
        w.writerow(row)
print(f"ADJ: {len(adjs)} → {adj_path}")

# Write adverbs
adv_path = os.path.join(BASE, "v2_new_adverbs.csv")
with open(adv_path, "w", encoding="utf-8", newline="") as f:
    w = csv.writer(f)
    w.writerow(["rank", "adverb", "comparative", "superlative", "ru", "collocations"])
    for row in advs:
        w.writerow(row)
print(f"ADV: {len(advs)} → {adv_path}")

# ─── Report missing translations ─────────────────────────────────────────────
missing = []
for rank, original, lemma, pos in entries:
    ru = get_translation(pos, lemma, original, rank)
    if ru.startswith("[") and ru.endswith("]"):
        missing.append((rank, pos, original, lemma, ru))

print(f"\n--- Missing translations: {len(missing)} ---")
for rank, pos, orig, lem, ru in missing[:50]:
    print(f"  rank={rank} {pos} orig={orig} lemma={lem}")
if len(missing) > 50:
    print(f"  ... and {len(missing) - 50} more")
